<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Ilvaite.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Auth\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ilvaite.Application\Ilvaite.Application.csproj" />
      <ProjectReference Include="..\Ilvaite.Core\Ilvaite.Core.csproj" />
    </ItemGroup>

</Project>
